# -*- coding: utf-8 -*-
"""Analisi_Ritmo_Alpha_EEG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ctet1Ldg9BI5mJk7LTYzXlKXQtYr7O3

CELLA DI SETUP
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install mne biosppy pyedflib -q

import mne
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.signal as signal
# %matplotlib inline

print("✅ Laboratorio configurato con successo!")
print(f"Strumenti pronti: MNE, NumPy, Pandas, SciPy, Matplotlib")

"""IMPORTAZIONE SEGNALE"""

data_path = mne.datasets.sample.data_path()
raw_fname = data_path / 'MEG' / 'sample' / 'sample_audvis_raw.fif'

raw = mne.io.read_raw_fif(raw_fname, preload=True, verbose=False)

# 3. Selezioniamo solo i sensori che ci servono
raw.pick_types(meg=False, eeg=True, eog=True)

print("✅ Dati caricati!")
print(f"Frequenza di campionamento: {raw.info['sfreq']} Hz")
print(f"Numero di elettrodi EEG: {len(raw.ch_names) - 1}") # -1 perché uno è l'EOG

# --- CELLA 3: VISUALIZZAZIONE DEL SEGNALE ---
import matplotlib.pyplot as plt

# 1. Definiamo quanti canali vogliamo vedere (es. 10)
# e per quanti secondi (es. 5 secondi)
n_canali = 10
secondi = 5

# 2. Creiamo il grafico
raw.plot(n_channels=n_canali, duration=secondi, title="Segnale EEG Grezzo (Originale)", scalings='auto')

plt.show()

# --- CELLA 4: IL FILTRAGGIO ---

raw_clean = raw.copy()

# 1. Applichiamo il filtro passa-banda da 1 a 40 Hz
raw_clean.filter(l_freq=1.0, h_freq=40.0)

raw_clean.plot(n_channels=10, duration=5, title="Segnale EEG Pulito (1-40 Hz)", scalings='auto')

plt.show()

# --- CELLA 5: ANALISI DELLE FREQUENZE (PSD) ---

# 1. Calcoliamo la PSD (Power Spectral Density)
psd = raw_clean.compute_psd(fmin=1.0, fmax=40.0)

# 2. Creiamo il grafico dello Spettro
# Questo grafico mostra la "potenza" (energia) sull'asse Y e la "frequenza" sull'asse X
psd.plot(picks='eeg', exclude='bads')

plt.show()

# --- CELLA 6: TABELLA DEI RISULTATI ---

risultati = {
    "Ritmo": ["Delta", "Theta", "Alpha", "Beta"],
    "Frequenza [Hz]": ["1 - 4", "4 - 8", "8 - 13", "13 - 30"],
    "Funzione": ["Sonno profondo", "Sonnolenza", "Relax/Occhi chiusi", "Attività motoria/Focus"]
}

df_report = pd.DataFrame(risultati)

print("📊 REPORT ANALISI NEUROSCIENTIFICA 📊")
print("-" * 40)
print(df_report.to_string(index=False)) # Mostra la tabella senza i numeri di riga
print("-" * 40)
print("\nAnalisi completata con successo!")